### ISSUE TITLE
Remove VM tests with CALL, CREATE, SELFDESTRUCT and the like, translating them into GeneralStateTests

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#415]

**Comment by ehildenb** [comment]
@pirapira any recent thoughts on this? I don't think we should do away with VMTests, but perhaps could limit their scope. It doesn't feel good to have KEVM have two versions of several opcodes, one just for VMTests.

Perhaps the VMTests that only deal with VM-related stuff could remain (eg. arithmetic, local memory ops, program counter ops), and anything that deals with Ethereum-specific state could be translated into GeneralStateTests instead?

I've become interested in this because I'm in the middle of refactoring the KEVM control-flow to make it more uniform to make doing proofs with KEVM easier (and also to support more uniform typed exceptions), but there are several spots where special cases are made for VMTests mode which are causing me headache.

**Comment by ehildenb** [comment]
Note that I do like having the VMTests around as an early target for implementers who have only made it through implementing the basic VM functionality. Similarly, someone might implement a wasm VM without making it extend to the ewasm, and would want to be able to run the wasm test-set without worrying about the extra host-functions added for ethereum.

**Comment by pirapira** [comment]
@ehildenb I have exactly the same reasons for keeping VMtests.  I changed the title of this issue, to remove only those problematic opcodes from VMtests.

**Comment by ehildenb** [comment]
Ok, then I guess we should discuss which tests should specifically be removed from the test-suite. At least the ones dealing with `CALL*`, `CREATE`, and `SELFDESTRUCT` I think. I will try to run the VMTests in non-VMTEST mode on KEVM and get a list of tests that break then post them here.

**Comment by ehildenb** [comment]
Here is a list of tests that fail when I disable all VMTESTS specific stuff: [disable-vmtests-mode-initial.txt](https://github.com/ethereum/tests/files/1872541/disable-vmtests-mode-initial.txt)

There are 40 total (including BLOCKHASH tests as well).

**Comment by ehildenb** [comment]
Full list of "problematic" opcodes: `BALANCE`, `EXTCODESIZE`, `EXTCODECOPY`, `CALL*`, `CREATE`. Actually doesn't seem to be any problem with `SELFDESTRUCT`.

**Comment by ehildenb** [comment]
So I have removed most of the dependencies of KEVM on VMTESTS mode (and disabled the relevant tests, which is coming to about 70ish now). One final issue remains, which is that the executing account's balance is asserted in the post-state of the VMTests. Because there is no transaction, there isn't a `gasPrice` to use, so a default `gasPrice = 1` is assumed.

I think that the post-state of the account should not be asserted in VMTests (or anything related to network-state/non-vm execution). I do think that the VMTests should be making assertions about the `gas` itself, but that is already happening separately over the `gas` component of state directly. For now I will disable the post-state balance assertions in KEVM to completely remove the semantics dependence on VMTESTS mode.

This makes me wonder about post-state storage assertions though. When talking with @winsvega at EthCC, it seemed that the storage was used to make assertions about computation by doing the computation then asserting that the resulting storage had some form, and certainly the tests are written that way. If we're taking the "separate the VM from the network state" seriously, I think even `SLOAD` and `SSTORE` don't belong there. In KEVM it is easy to also make assertions about things like the local memory and stack, but I get the feeling it won't be super easy in other clients because they are probably already set up to be able to do state-dumps of network state, but maybe not VM execution state.

**Comment by winsvega** [comment]
Just to note. 
Storage is used in state tests as a mean to check the execution result.
In VMTests gasUsed is the indicator of bytecode execution results. 
The storage check was added later and is used when generating the tests.

**Comment by pirapira** [comment]
I picked the first one
```
VMTests/vmBlockInfoTest/blockhash258Block.json
```

I'll see if this is worth translating to GeneralStateTest, and work accordingly.  With the feedback on this one, I can continue with the others.

EDIT: well, this one looks like just testing the blockhash mock for the VM tests.  I'm going to remove these, no translations.

**Comment by pirapira** [comment]
@ehildenb why is VMTests/vmRandomTest/201503120909PYTHON.json listed?  Is it because of `CALLVALUE` and `CALLDATALOAD`?

**Comment by ehildenb** [comment]
Commit which drops VMTESTS mode from KEVM semantics: https://github.com/kframework/evm-semantics/pull/178/commits/902a7ed1401ebbfd430f1d78c8e9ead5ee68ad94

**Comment by pirapira** [comment]
I tried the branch, and I can see some of the listed VM tests can stay, like https://github.com/pirapira/evm-semantics/commit/e350e757173ab5c34058a96c8e54533dfb5982ca

**Comment by pirapira** [comment]
* [x] #444  VMTests/vmBlockInfoTest/blockhash258Block.json
* [x] #444 VMTests/vmBlockInfoTest/blockhash257Block.json
* [x] #444 VMTests/vmBlockInfoTest/blockhashMyBlock.json
* [x] #444 VMTests/vmBlockInfoTest/blockhashOutOfRange.json
* [x] #444 VMTests/vmBlockInfoTest/blockhashInRange.json
* [x] #444 VMTests/vmBlockInfoTest/blockhashNotExistingBlock.json
* [x] can stay VMTests/vmRandomTest/201503120909PYTHON.json
* [x] can stay VMTests/vmRandomTest/201503120317PYTHON.json
* [x] can stay VMTests/vmRandomTest/201503110050PYTHON.json
* [x] can stay VMTests/vmRandomTest/201503102300PYTHON.json
* [x] #445 VMTests/vmRandomTest/randomTest.json (has `BALANCE`)
* [x] can stay VMTests/vmRandomTest/201503102148PYTHON.json
* [x] can stay VMTests/vmRandomTest/201503120547PYTHON.json
* [x] #445 VMTests/vmRandomTest/201503110226PYTHON_DUP6.json (has `BALANCE`)
* [x] can stay VMTests/vmRandomTest/201503102037PYTHON.json
* [x] can stay VMTests/vmRandomTest/201503110526PYTHON.json

The rest seems obviously dependent on the world state.

* [ ] VMTests/vmEnvironmentalInfo/balanceAddressInputTooBigRightMyAddress.json (should be a general state test)
* [ ] VMTests/vmEnvironmentalInfo/env1.json (perhaps removable)
* [ ] VMTests/vmEnvironmentalInfo/ExtCodeSizeAddressInputTooBigRightMyAddress.json (should be a general state test)
* [ ] VMTests/vmEnvironmentalInfo/balance0.json (should be a general state test)
* [ ] VMTests/vmEnvironmentalInfo/extcodecopy0AddressTooBigRight.json (should be a general state test)
* [ ] VMTests/vmEnvironmentalInfo/balanceCaller3.json (should be a general state test)
* [ ] VMTests/vmEnvironmentalInfo/balanceAddressInputTooBig.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/ABAcalls0.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/CallRecursiveBomb0.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/callstatelessToNameRegistrator0.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/CallToNameRegistrator0.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/CallRecursiveBomb2.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/CallToReturn1.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/callstatelessToReturn1.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/CallRecursiveBomb3.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/ABAcallsSuicide1.json (should e a general state test)
* [ ] VMTests/vmSystemOperations/PostToNameRegistrator0.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/callcodeToNameRegistrator0.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/PostToReturn1.json (should be a general statet test)
* [ ] VMTests/vmSystemOperations/callcodeToReturn1.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/createNameRegistrator.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/CallToPrecompiledContract.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/ABAcallsSuicide0.json (should be a general state test)
* [ ] VMTests/vmSystemOperations/CallRecursiveBomb1.json (should be a general state test)

**Comment by winsvega** [comment]
I would suggest the `vmmode`  while executing a state test. to just compare the trace logs coming from its execution. 
this way should be possible to run any state test as vmtest. 

for remote clients can add explicit field in the generated test stating the gas usage because not able to check against posthash I suppose.

**Comment by qbzzt** [comment]
Note that almost all the VMTests will be GeneralStateTests as soon as @winsvega merges https://github.com/ethereum/tests/pull/791

**Comment by qbzzt** [comment]
> I would suggest the `vmmode` while executing a state test. to just compare the trace logs coming from its execution.
> this way should be possible to run any state test as vmtest.
> 
> for remote clients can add explicit field in the generated test stating the gas usage because not able to check against posthash I suppose.

Do you mean `--vmtraceraw`? 

BTW, in case somebody doesn't know it yet, http://retesteth.ethdevops.io/web/index.php lets you generate the traces on the web without having to run anything locally. Better usability.

**Comment by winsvega** [comment]
@qbzzt here the problem was that some clients using vmtests while not supporting calls or some specific evm opcodes.

**Comment by qbzzt** [comment]
Do we want a tool that you can ask "give me all the GeneralStateTests/VMTests without these opcodes" and get the list?

**Comment by winsvega** [comment]
not really. 
the VMTests are now moved to Legacy. 
all the cases are migrated to GeneralStateTests
