### ISSUE TITLE
[Meta] Documentation Improvements

### ISSUE THREAD

**Issue by holgerd77** [ethereum/tests#555]
I will use this issue to collect different ideas and work tasks for documentation update rounds. If you have ideas for improving the docs coming along with work on issues or PRs optimally make a note there and link to this thread.

**Comment by holgerd77** [comment]
Documentation Updates, next round:

- [x] Note on coinbase touch simulation, see [comment](https://github.com/ethereum/tests/pull/539#issuecomment-439998297)
- [x] Move test set sanitation [section](https://github.com/ethereum/tests#test-set-sanitation) from ``README`` to docs
- [x] Add some Yaml test example from @hugo-dc, see https://github.com/ethereum/tests/pull/543#issuecomment-442260739
- [ ] Add [client installation instructions](https://github.com/ethereum/tests/issues/531#issuecomment-438631210) for tagged releases

**Comment by winsvega** [comment]
I think tests affected by coinbase touch simulation should be moved from state tests to blockchain 
it is a blockchain logic and misleading to implement it on all state tests.

**Comment by holgerd77** [comment]
@winsvega yes, that probably makes sense. I will try to state this in the doc section that this is just the "how it currently is" and not the optimal situation and that this might change in the future.

**Comment by holgerd77** [comment]
Client installation instructions should be added to the docs as well (added the task to the list above), just had to look this up myself here again for `ethereumjs-testing` library update. 😛

**Comment by winsvega** [comment]
there was major documentation iprovement: 
https://ethereum-tests.readthedocs.io/en/latest/
